defaults:
  - agent: drqn
  - override hydra/launcher: submitit_local

# task settings
task: "minigrid"
n_envs: 1
animals: [SC03]
# enc_type: linear 
# discount: 0.99
# train settings
num_train_steps: 1000000
num_seed_steps: 1 #4000
# eval
eval_every_steps: 100 #250
num_eval_configurations: 2
# replay buffer
replay_buffer_size: 1 #256 128 #10000
# nstep: ${agent.nstep}
batch_size: ${agent.batch_size}
sequence_length: ${agent.sequence_length}
# snapshot
snapshots: [250, 500, 1000, 2000]
# snapshot_dir: ../../../models/${task}/${animals[0]}/${agent.name}/${seed}
# snapshot_dir: ../../../model_data/front_view/models/${agent.name}/${seed}
snapshot_ts: 15999 #14901  14999 
# snapshot_ts: 14901 
# snapshot_ts: 15001 
# snapshot_ts: 4001
# snapshot_ts: 0
snapshot_base_dir: ../../../models # DQN model 
# snapshot_base_dir: ../../../models/${task}/${animals[0]}/${agent.name}/${seed}
# path for drqn model
# snapshot_base_dir: ../../../model_data/front_view/models/${agent.name}/1
# snapshot_base_dir: ../../../model_data/front_view/models/${agent.name}/${seed}
#utils
data_source: animal # select between [animal, random, none]
csv_path: "/home/rh19400/continual_rl/animal_data/trials/${animals[0]}.csv" # path where the animal recordings are stored
trials: 16000
# misc
seed: 1
device: cuda
save_video: false
# save_train_video: false
use_tb: false
use_wandb: false
# use_amp: false
# use_onnx: false
# experiment
experiment: exp
save_activations: false
save_heatmaps_and_stats: true


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm


