# @package agent
_target_: agent.drqn.DRQNAgent
name: drqn
num_obs: ??? # to be specified later
num_actions: ??? # to be specified later
neurons_rnn_layer: 200 #50
hidden_size: 200
device: ${device}
lr: 1e-4
gamma: 0.9
sequence_length: 128 
use_tb: ${use_tb}
use_wandb: ${use_wandb}
batch_size: 1
tau: 0.01
nsteps: 1
update_every_steps: 1
max_eps: 0.9
min_eps: 0.1
eps_decay: 0.9
n_heads: 1
